version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: '/packages/agent_dart'
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: '/packages/agent_dart/example'
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: '/packages/flutter_agent_dart'
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: '/packages/flutter_agent_dart/example'
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: '/packages/agent_dart/native'
    schedule:
      interval: weekly
