dart_format_line_length: 80
rust_input:
  - 'rust/agent_dart/src/api.rs'
dart_output:
  - 'lib/bridge/ffi/ffi_bridge.dart'
c_output:
  - 'rust/headers/bridge_generated.h'
extra_c_output_path:
  - 'ios/Classes/'
  - 'macos/Classes/'
#llvm_path:
#  - 'X:\\SDK\\LLVM'
