name: agent_dart
description: |
  An agent library built for Internet Computer,
  a plugin package for dart and flutter apps.
  Developers can build ones to interact with Dfinity's blockchain directly.
repository: https://github.com/AstroxNetwork/agent_dart
version: 1.0.0-dev.20

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  archive: ^3.3.8
  args: ^2.3.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  cbor: ^4.1.0
  collection: ^1.16.0
  convert: ^3.0.1
  crypto: ^3.0.2
  ffi: ^2.0.1
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: '>=1.82.0 <1.83.0'
  http: ^1.0.0
  js: ^0.6.4
  meta: ^1.7.0
  path: ^1.8.1
  pinenacl: ^0.5.1
  pointycastle: ^3.6.0
  protobuf: ^3.1.0
  recase: ^4.0.0
  tuple: ^2.0.0
  typed_data: ^1.3.1
  uuid: ^3.0.6
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.1
  flutter_test:
    sdk: flutter
  ffigen: ^9.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.astrox.agent_dart
        pluginClass: AgentDartPlugin
      ios:
        pluginClass: AgentDartPlugin
      linux:
        pluginClass: AgentDartPlugin
      macos:
        pluginClass: AgentDartPlugin
      windows:
        pluginClass: AgentDartPlugin

false_secrets:
  - /rust/ed_compact/src/pem.rs
  - /test/fixture/*.pem
