name: agent_dart
description: |
  An agent library built for Internet Computer,
  a plugin package for dart and flutter apps.
  Developers can build ones to interact with Dfinity's blockchain directly.
version: 0.1.23
homepage: https://github.com/AstroxNetwork/agent_dart

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  archive: ^3.3.0
  args: ^2.1.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  cbor: ^4.1.0
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.1
  ffi: ^1.1.1
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.4
  js: ^0.6.3
  path: ^1.8.0
  pinenacl: ^0.3.1
  pointycastle: ^3.1.2
  protobuf: ^2.0.0
  recase: ^4.0.0
  tuple: ^2.0.0
  typed_data: ^1.3.0
  uuid: ^3.0.4
  validators: ^3.0.0
  meta: ^1.3.0
  basic_utils: ^3.9.4

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

false_secrets:
  - /test/fixture/*.pem

flutter:
  plugin:
    platforms:
      android:
        package: com.astrox.agent_dart
        pluginClass: AgentDartPlugin
      ios:
        pluginClass: AgentDartPlugin
      linux:
        pluginClass: AgentDartPlugin
      macos:
        pluginClass: AgentDartPlugin
      windows:
        pluginClass: AgentDartPlugin
      web:
        pluginClass: AgentDartPlugin
        fileName: agent_dart_web.dart
