[package]
name = "ed_compact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["random", "std"]
pem = ["ct-codecs"]
random = ["getrandom"]
traits = ["ed25519"]
self-verify = []
blind-keys = []
std = []
opt_size = []

[dependencies]
ct-codecs = { version = "1.1", optional = true }
getrandom = { version = "0.2", optional = true }
ed25519 = { version = "1.2", optional = true }

[dev-dependencies]
getrandom = "0.2"
ct-codecs = "1.1"

[build-dependencies]
flutter_rust_bridge_codegen = "~1.82"
flutter_rust_bridge_macros = "~1.82"
