[package]
name = "agent_dart"
version = "0.0.1"
authors = ["neeboo <ghostcorn@gmail.com>"]
edition = "2018"

[lib]
name = "agent_dart"
crate-type = ["staticlib", "cdylib"]

[dependencies]
hex = "0.4.2"
rustc-hex = "2.1.0"
hmac = { version = "0.11.0", default-features = false }
pbkdf2 = { version = "0.8.0", default-features = false }
sha2 = { version = "0.9.5", default-features = false }
ethsign = { version = "0.8.0", default-features = false, features = ["pure-rust"] }
derivation-path = { version = "0.1.3", default-features = false }
serde_json = "1.0"

[dev-dependencies]
hex-literal = "0.3.1"

[profile.release]
debug = true