name: agent_dart_ffi
description: |
  An agent library built for Internet Computer,
  a plugin package for dart and flutter apps.
  Developers can build ones to interact with Dfinity's blockchain directly.
repository: https://github.com/AstroxNetwork/agent_dart
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_rust_bridge: ^1.72.0
  ffi: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  ffigen: ^7.2.9

false_secrets:
  - /rust/ed_compact/src/pem.rs
  - /test/fixture/*.pem
