name: agent_dart_ffi
description: |
  An agent library built for Internet Computer,
  a plugin package for dart and flutter apps.
  Developers can build ones to interact with Dfinity's blockchain directly.
version: 1.0.0
homepage: https://github.com/AstroxNetwork
repository: https://github.com/AstroxNetwork/agent_dart
issue_tracker: https://github.com/AstroxNetwork/agent_dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_rust_bridge: 1.82.6
  freezed_annotation: ^2.2.0
  freezed: ^2.0.3+1
  ffi: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.11
  ffigen: ^8.0.2

false_secrets:
  - /rust/ed_compact/src/pem.rs
  - /test/fixture/*.pem
