name: agent_dart
description: A new Flutter FFI plugin project.
version: 1.0.0
homepage: https://github.com/AstroxNetwork
repository: https://github.com/AstroxNetwork/agent_dart
issue_tracker: https://github.com/AstroxNetwork/agent_dart/issues
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  agent_dart_base:
    git:
      url: https://github.com/AstroxNetwork/agent_dart
      path: packages/agent_dart_base
      ref: bdk_lite

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
