name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Replace symlinks before publish
        run: ./scripts/replace_symlinks_before_publish.sh
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          force: true
          skipTests: true
          suppressBuildRunner: true
