name: Runnable (stable)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Analyze on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v3
      - run: cargo build --package=agent_dart
      - run: cd packages/agent_dart_base && dart test ./test/agent_dart_base_test.dart
      - name: Replace symlinks before publish
        run: ./scripts/replace_symlinks_before_publish.sh
      - name: Publish dry run
        run: dart pub publish --dry-run
        if: github.repository == 'AstroxNetwork/agent_dart'
